### ISSUE TITLE
Missing streets in api that are in openstreetmap

### ISSUE THREAD

**Issue by OnlyThatGuy** [openpotato/openplzapi.data#1]
Hi,
it seems there are some streets missing that can be found if you search in openstreetmap.
Maybe there is an error while converting data? Or is there a reason for filtering out some streets?
E.g. Theatinerstraße in munich

**Comment by fstueber** [comment]
It seems Theatinerstraße is for pedestrian only. I have to investigate on this. If you have more examples, please share.

**Comment by fstueber** [comment]
New version published. Data quality has improved. Theatinerstr. in Munich is now part of the data. Please check other streets you had in mind. Thanks a lot for the feedback!

**Comment by OnlyThatGuy** [comment]
Thanks for the fast reply and fix! Everything seems to work now.

**Comment by OnlyThatGuy** [comment]
Hi again,
i got another street found on https://www.openstreetmap.org/search?query=Sch%C3%BCtzenstra%C3%9Fe%20Bad%20Oldesloe#map=19/53.81034/10.36661
but not via openplzapi

**Comment by fstueber** [comment]
When I search for

`https://openplzapi.org/de/Streets?name=Sch%C3%BCtzenstr.&locality=Bad%20Oldesloe&page=1&pageSize=10`

I get this:

```  json
[
  {
    "name": "Schützenstr.",
    "postalCode": "23843",
    "locality": "Bad Oldesloe",
    "municipality": {
      "key": "01062004",
      "name": "Bad Oldesloe, Stadt",
      "type": "Stadt"
    },
    "district": {
      "key": "01062",
      "name": "Stormarn",
      "type": "Kreis"
    },
    "federalState": {
      "key": "01",
      "name": "Schleswig-Holstein"
    }
  }
]
```

Am I missing something?
