### ISSUE TITLE
Two entries for postal code 63263

### ISSUE THREAD

**Issue by rockstaedt** [openpotato/openplzapi.data#3]
Hi there!

Thanks a lot for this cool API. We are using it to prefill city and district names when a postal code is entered.

However, we came across the issue that a request for the postal code 63263 returns two entries:

* Request: https://openplzapi.org/de/Localities?postalCode=63263&page=1&pageSize=10
* Result:

 ```json
[
    {
        "postalCode": "63263",
        "name": "Frankfurt am Main",
        "municipality": {
            "key": "06412000",
            "name": "Frankfurt am Main, Stadt",
            "type": "Kreisfreie_Stadt"
        },
        "district": {
            "key": "06412",
            "name": "Frankfurt am Main, Stadt",
            "type": "Kreisfreie_Stadt"
        },
        "federalState": {
            "key": "06",
            "name": "Hessen"
        }
    },
    {
        "postalCode": "63263",
        "name": "Neu-Isenburg",
        "municipality": {
            "key": "06438009",
            "name": "Neu-Isenburg, Stadt",
            "type": "Stadt"
        },
        "district": {
            "key": "06438",
            "name": "Offenbach",
            "type": "Landkreis"
        },
        "federalState": {
            "key": "06",
            "name": "Hessen"
        }
    }
]
```

When I search for 63263, I only get Neu-Isenburg as the city and not Frankfurt am Main. Since we only use the first result, user were complaining that the wrong city was prefilled. I am the opinion that postal codes in Germany are unique, aren't they?

Is this intended or can it be fixed? I am happy to help if I am directed in the right direction :)

**Comment by rockstaedt** [comment]
Ah I also searched the `street.csv` file for the postal code. 

63263 in combination with Neu-Isenburg exists over 200 times whereas 63263 in combination with Frankfurt am Main only three times.

**Comment by fstueber** [comment]
This seems to be a bug in merging OSM data with GV100AD data.

**Comment by rockstaedt** [comment]
Alright :) And where can this be fixed? The repo only contains the data, doesn't it?

**Comment by fstueber** [comment]
Yes, exactly. The workflow for extracting and merging data is not yet open sourced. I will try to look into this in the coming days.

**Comment by rockstaedt** [comment]
Okidoki, thanks a lot!

**Comment by rockstaedt** [comment]
Any news here?

**Comment by fstueber** [comment]
No yet. Sorry. But it is not forgotten :-)

**Comment by fstueber** [comment]
Fixed. Please check. Please check also new version of OpenPLZ API: https://www.openplzapi.org/en/change-log/
