### ISSUE TITLE
Missing Street

### ISSUE THREAD

**Issue by alexander-rebello** [openpotato/openplzapi.data#4]
Hi there,

First, thanks for this API, very usefull. When using it to autofill addresses, one of our customers noticed a missing street in Germany, Wuppertal, 42327: "Arndtstraße"
I've tried multiple ways of writing it, also "Arndtstr", which gives me multiple results from other cities. When checking the OpenStreetMap website, I actually am able to find it. So I'm not quite sure if I'm doing something wrong here or if it's just missing in the data? Thanks in advance

**Comment by fstueber** [comment]
Hi, this gives me the street:
``` url
https://openplzapi.org/de/Streets?name=Arndtstr&postalCode=42327&page=1&pageSize=10
```
Or am I missing something?

**Comment by fstueber** [comment]
What about this?
``` url
https://openplzapi.org/de/Streets?name=Arndtstr&locality=Wuppertal&page=1&pageSize=10
```

**Comment by fstueber** [comment]
Or this:
``` url
https://openplzapi.org/de/Streets?name=%5EArndtstr&locality=Wuppertal&page=1&pageSize=10
```
Difference: Street name must START with "Arndtstr" (expressed via reg expr "^Arndtstr")

**Comment by alexander-rebello** [comment]
Yeah true, but for that i would need to figure out what part of the search string is the city and what part is the street. Imagine an input like the google maps search bar.

**Comment by fstueber** [comment]
Ah ok, I see. Thats indeed missing at the moment. But you can emulate this via regular expressions:
``` url
https://openplzapi.org/de/Streets?name=%5EArndtstr%7C%5EWuppertal&locality=%5EArndtstr%7C%5EWuppertal&page=1&pageSize=10
```
It says: Give me all streets where the street name starts with "Arndtsr" OR "Wuppertal", and the location starts "Arndtsr" OR "Wuppertal". This should give you a hint in the right direction.

**Comment by alexander-rebello** [comment]
Ok perfect, thank you very much!
