### ISSUE TITLE
Dörfer/Ortsteile

### ISSUE THREAD

**Issue by Lure5134** [openpotato/openplzapi.data#6]
Hi, ich habe mal ein paar Verständnis Fragen.
Ich würde die API gerne als Autovervollständigung nutzen, allerdings findet man gewisse Orte in der streets.csv nicht als Orte.
Bspws. Peheim
Laut Wikipedia: https://de.wikipedia.org/wiki/Peheim ein Ort
Auch bei photon.komoot.io taucht Peheim als Ort auf:
https://photon.komoot.io/api/?q=peheim&osm_tag=place
"Kleinere" Orte fehlen leider und die entsprechenden Straßen werden den Gemeinden zugewiesen.
Ist das beabsichtigt?

Eine Weitere Frage, die ich hätte ist das teilweise Straßennamen anders sind als bei Open Street Maps.
Bspws gibt es in Peheim die Straße "Kolpingstraße".
In der CSV-Datei taucht die Straße aber unter dem Namen "Kolpingstr." auf.
Hat das einen besonderen Grund?

**Comment by fstueber** [comment]
Hallo. Das ist nicht beabsichtigt, es ist das Ergebnis des Datenextraktes aus OSM. Wie genau das funktioniert, ist hier ganz gut erklärt: https://github.com/openpotato/openplzapi.data/blob/main/README.md.

Die Sache mit dem "str." ist so gewollt. Alle Straßennamen werden normalisiert. Da war die Entscheidung, alle mit der Endung "strasse" oder "straße" oder "str.". Ich hab mich für "str." entschieden, weil das kurz ist und es auch die Standardendung bei Postdirekt ist: https://www.postdirekt.de/plzserver/

**Comment by fstueber** [comment]
Peheim ist in OSM als Ortsteil von Molbergen definiert. Geografisch allerdings nur als Punkt, nicht als Fläche. Unter [https://www.suche-postleitzahl.org/](https://www.suche-postleitzahl.org/molbergen.l5242) (basiert auch auf OSM) das gleiche Bild. Es ist keine Zuordnung Straßen zu Peheim möglich.

Zum Thema "Str": Das ist der Eintrag unter PostDirekt.
![image](https://github.com/user-attachments/assets/55844838-59bf-423e-bed7-bcd901cb7f29)

**Comment by mark-langer** [comment]
Hi zusammen,

vielleicht finden wir ja gemeinsam noch eine Lösung für das Problem. Wir haben die gleiche Anforderung wie @Lure5134 .

Weil diese Issue schon geschlossen ist, habe ich nochmal eine ähnliche erstellt, um besser zu verstehen...
* _Warum_ das Mapping des Ortsteils über die Suche von Open Street Map funktioniert, aber für diesen Export noch relativ schwierig ist.
* Ob die Routine zur Erstellung der Export ge-open-sourced werden kann, damit wir auch beitragen können, das Projekt hinsichtlich der Ortsteile etwas zu erweitern.

Das Ziel könnte ja sein, mit diesem Projekt deutschen Software-Projekten zu erleichtern, ihren Nutzern gute Adress-Autocompletes zu geben, ohne gleich knapp 2.000 € im Jahr an die Deutsche Post zahlen zu müssen (Mindestvertragslaufzeit 2 Jahre).

**Comment by fstueber** [comment]
Ja, man könnte probieren, beide Ansätze miteinander zu kombinieren: https://github.com/openpotato/openplzapi.data/issues/7#issuecomment-2531000431

**Comment by fstueber** [comment]
Nur als abschließende Info: Der OSM-Crawler für OpenPLZ API ist jetzt auch Open Source: https://github.com/openpotato/openplzapi.osm
